---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  annotations:
    qubership.cloud/start.stage: '2'
  labels:
    name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  ports:
    -   name: web
        port: 8080
        targetPort: 8080
  selector:
    name: '{{ .Values.SERVICE_NAME }}'
  {{ if  eq .Values.K8S_SERVICE_TYPE "HEADLESS" }}
  clusterIP: None
  {{ end }}
