name: Go build (PR)

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: go-build-pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    uses: taurmorchant/workflows-test/.github/workflows/go-build-with-sonar.yaml@main
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}